---
version: '3'

services:
  docker-registry:
      container_name: docker-registry
      image: registry:2
      ports:
        - 5000:5000
      restart: always
      volumes:
        - ./volume:/var/lib/registry